groups:
- name: vulnerability-management
  rules:
  - alert: HighCriticalVulnerabilities
    expr: vulnerability_count{priority="Critical",status="open"} > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High number of critical vulnerabilities detected"
      description: "{{ $value }} critical vulnerabilities are currently open"

  - alert: SLABreach
    expr: vulnerability_sla_breach_count > 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "SLA breach detected"
      description: "{{ $value }} vulnerabilities have breached their SLA"

  - alert: LLMServiceDown
    expr: up{job="vuln-llm"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "LLM service is down"
      description: "The LLM analyzer service has been down for more than 2 minutes"

  - alert: ParserServiceDown
    expr: up{job="vuln-parser"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Parser service is down"
      description: "The Nmap parser service has been down for more than 2 minutes"
