---
- name: Security Patch Management Playbook
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Refresh package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Apply security patches (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: safe
        update_cache: false  # Already updated above
      when: ansible_os_family == "Debian"
      # Note: apt module doesn't have direct security-only option
      # For security-only updates, consider using shell module with apt-get

    - name: Apply security patches (RHEL/CentOS/Fedora)
      ansible.builtin.yum:
        name: '*'
        state: latest
        security: true
        update_cache: true
      when: ansible_os_family == "RedHat"

    - name: Check if reboot is required (Debian/Ubuntu)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required (RHEL/CentOS - alternative method)
      ansible.builtin.shell: |
        needs-restarting -r
      register: reboot_required_rhel
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Reboot server if required (Debian/Ubuntu)
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible Patch Management"
        reboot_timeout: 900
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: 
        - ansible_os_family == "Debian"
        - reboot_required_file.stat.exists

    - name: Reboot server if required (RHEL/CentOS)
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible Patch Management"
        reboot_timeout: 900
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: 
        - ansible_os_family == "RedHat"
        - reboot_required_rhel.rc == 1
