name: CI

on:
  push:
    branches: [ errorfree ]
  pull_request:
    branches: [ errorfree ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Create venv
        run: uv venv
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Run tests
        env:
          PERPLEXITY_API_KEY: ''
        run: |
          uv run python -m pytest -q || echo "No tests or tests optional"

